
import { type Lang, type ShotOption, type ToneOption, type ArtToneOption } from './types';

export const PANEL_COUNT = 4;
export const DEFAULT_WIDTH = 1024;
export const RATIO_W = 1;
export const RATIO_H = 1;
export const SEP = 4;
export const MARGIN = 16;
export const SITE_NAME = 'MangaMatic';
export const FILE_BASENAME = 'manga-matic';

export const shotOptions: ShotOption[] = [
  { value: 'wide',       labelKey: 'shot.wide.label',       titleKey: 'shot.wide.title' },
  { value: 'waist',      labelKey: 'shot.waist.label',      titleKey: 'shot.waist.title' },
  { value: 'closeup_A',  labelKey: 'shot.closeup_A.label',  titleKey: 'shot.closeup_A.title' },
  { value: 'closeup_B',  labelKey: 'shot.closeup_B.label',  titleKey: 'shot.closeup_B.title' },
  { value: 'two_shot',   labelKey: 'shot.two_shot.label',   titleKey: 'shot.two_shot.title' },
  { value: 'reaction_A', labelKey: 'shot.reaction_A.label', titleKey: 'shot.reaction_A.title' },
  { value: 'reaction_B', labelKey: 'shot.reaction_B.label', titleKey: 'shot.reaction_B.title' },
  { value: 'ots_A',      labelKey: 'shot.ots_A.label',      titleKey: 'shot.ots_A.title' },
  { value: 'ots_B',      labelKey: 'shot.ots_B.label',      titleKey: 'shot.ots_B.title' },
];

export const artToneOptions: ArtToneOption[] = [
  { value: 'mono-screen',  labelKey: 'tone.mono-screen' },
  { value: 'line-bold',    labelKey: 'tone.line-bold' },
  { value: 'soft-mono',    labelKey: 'tone.soft-mono' },
  { value: 'shonen-ink',   labelKey: 'tone.shonen-ink' },
  { value: 'shojo-mono',   labelKey: 'tone.shojo-mono' },
  { value: 'seinen-real',  labelKey: 'tone.seinen-real' },
  { value: 'gekiga',       labelKey: 'tone.gekiga' },
  { value: 'retro-90s',    labelKey: 'tone.retro-90s' },
  { value: 'horror-ink',   labelKey: 'tone.horror-ink' },
  { value: 'sumi-brush',   labelKey: 'tone.sumi-brush' },
  { value: 'hatch',        labelKey: 'tone.hatch' },
  { value: 'chibi-gag',    labelKey: 'tone.chibi-gag' },
  { value: 'flat-color',   labelKey: 'tone.flat-color' },
  { value: 'pastel-color', labelKey: 'tone.pastel-color' },
  { value: 'webtoon-color',labelKey: 'tone.webtoon-color' },
];

export const toneOptions: ToneOption[] = [
  { value: 'story.boke_tsukkomi' },
  { value: 'story.kishotenketsu' },
  { value: 'story.running_gag' },
  { value: 'story.misunderstanding' },
  { value: 'story.slice_of_life' },
  { value: 'story.meta' },
  { value: 'story.heartful_blunder' },
  { value: 'story.absurd_silence_meta' },
];


export const translations: Record<Lang, Record<string, string>> = {
  en: {
    'header.preview': 'Preview vertical composition',
    'header.reset': 'Reset',
    'header.language': 'Language',
    'preview.title': '4-panel Preview',
    'preview.download': 'Download PNG',
    'preview.close': 'Close',
    'confirm.cancel': 'Cancel',
    'confirm.overwrite': 'Overwrite',
    'canvas.title': 'Canvas Editor',
    'canvas.draw': 'Draw',
    'canvas.erase': 'Erase',
    'canvas.thickness': 'Thickness',
    'canvas.clear': 'Clear',
    'canvas.save': 'Save',
    'form.tone': 'Tone',
    'form.artStyle': 'Art style',
    'shot.wide.label': 'Wide (Intro)',
    'shot.wide.title': 'Wide angle showing scene and spatial relation',
    'shot.waist.label': 'Waist shot',
    'shot.waist.title': 'Medium composition showing chest to waist',
    'shot.closeup_A.label': 'A Close-up',
    'shot.closeup_A.title': "Emphasizes A's expression",
    'shot.closeup_B.label': 'B Close-up',
    'shot.closeup_B.title': "Emphasizes B's expression (when using B)",
    'shot.two_shot.label': 'Two-shot',
    'shot.two_shot.title': 'Shows relationship between A and B (when using B)',
    'shot.reaction_A.label': 'A Reaction',
    'shot.reaction_A.title': "Emphasizes A's reaction or retort",
    'shot.reaction_B.label': 'B Reaction',
    'shot.reaction_B.title': "Emphasizes B's reaction (when using B)",
    'shot.ots_A.label': 'A over-the-shoulder',
    'shot.ots_A.title': 'Shows target from A\'s shoulder',
    'shot.ots_B.label': 'B over-the-shoulder',
    'shot.ots_B.title': 'Shows target from B\'s shoulder (when using B)',
    'story.boke_tsukkomi': 'Setup→Retort→Twist Ending',
    'story.kishotenketsu': 'Kishōtenketsu',
    'story.running_gag': 'Running gag',
    'story.misunderstanding': 'Misunderstanding',
    'story.slice_of_life': 'Slice of life',
    'story.meta': 'Meta',
    'story.heartful_blunder': 'Heartful → blunder → redemption',
    'story.absurd_silence_meta': 'Absurd → silence → meta punchline',
    'tone.mono-screen': 'Monochrome (halftone)',
    'tone.line-bold': 'Bold lines / high contrast',
    'tone.soft-mono': 'Soft monochrome',
    'tone.shonen-ink': 'Shonen manga (speed lines / impact)',
    'tone.shojo-mono': 'Shojo manga (delicate / sparkles)',
    'tone.seinen-real': 'Seinen manga (realistic / heavy tones)',
    'tone.gekiga': 'Gekiga (shadows / serious)',
    'tone.retro-90s': '90s style (retro halftone)',
    'tone.horror-ink': 'Horror (solid blacks / scratch)',
    'tone.sumi-brush': 'Ink brush (brush strokes / rough)',
    'tone.hatch': 'Hatching shadows',
    'tone.chibi-gag': 'Chibi / gag',
    'tone.flat-color': 'Flat color',
    'tone.pastel-color': 'Pastel color',
    'tone.webtoon-color': 'Webtoon (color)',
    'panel.noShot': 'No layout (optional)',
    'placeholder.notGenerated': 'Not generated',
    'overlay.generatingCharacter': 'Generating character image…',
    'overlay.composingImages': 'Composing images…',
    'overlay.generatingScript': 'Generating script…',
    'overlay.generatingPanels': 'Creating 4 panels…',
    'alert.characterGenFailed': 'Character generation failed',
    'alert.panelGenFailed': 'Panel generation failed',
    'alert.mergeFailed': 'Image composition failed',
    'alert.scriptGenFailed': 'Script generation failed',
    'confirm.resetAll': 'Reset everything?',
    'confirm.replaceCanvas': 'Replace canvas content with the selected image?',
    'lang.en': 'English',
    'lang.ja': 'Japanese',
    'card.autoScript.title': 'Auto-generate script from overview',
    'card.autoScript.subtitle': 'Enter text to auto-generate script and characters',
    'card.characters.title': 'Characters',
    'card.characters.subtitle': 'Up to two; upload references or generate with AI (optional)',
    'form.overview': 'Overview',
    'placeholder.overviewExample': 'e.g., A brags about AI → B retorts → A makes excuses → B delivers the punchline',
    'option.autoPlan.script': 'Generate script only',
    'option.autoPlan.scriptCharacters': 'Generate script and characters only',
    'option.autoPlan.full': 'Create four panels',
    'button.create': 'Create',
    'label.useCharacterB': 'Use character B',
    'button.aiGenerate': 'AI Generate',
    'placeholder.characterPrompt': 'Style descriptors, tone, NG words, etc.',
    'button.addReference': 'Add reference',
    'status.draft': 'Draft',
    'status.generating': 'Generating',
    'status.done': 'Done',
    'status.failed': 'Failed',
    'panel.edit': 'Panel Edit',
    'button.generate': 'Generate',
    'button.regenerate': 'Regenerate',
    'button.savePng': 'Save PNG',
    'button.savePngWithSpeech': 'Save PNG (with speech)',
    'panel.script': 'Script',
    'label.description': 'Description (scene)',
    'placeholder.descriptionExample': 'e.g., A proudly stands before a PC. B watches with arms crossed.',
    'label.lineA': 'Line (A)',
    'placeholder.lineA': 'Short line for A',
    'label.lineB': 'Line (B)',
    'placeholder.lineB': 'Short line for B',
    'placeholder.layoutHint': 'Layout hint: A left → B right, etc.',
    'label.rough': 'Rough (reference)',
    'label.showTools': 'Show tools',
    'button.drawRough': 'Draw rough',
    'button.loadImage': 'Load image',
    'message.noRough': 'No rough sketch. Use "Draw rough" or "Load image" to add one.',
    'confirm.replace': 'Replace',
    'character.A': 'Character A',
    'character.B': 'Character B',
    'guide.title': 'How to use',
    'guide.message': 'Enter content and style tone, then press Generate to automatically create a four-panel comic.',
    'guide.close': 'OK',
    'tooltip.overview': 'Short summary used to auto-generate the script.',
    'tooltip.tone': 'Select the story tone.',
    'tooltip.artStyle': 'Select the overall art style.',
    'tooltip.autoPlan': 'Choose what to generate automatically.',
    'tooltip.useCharacterB': 'Enable to include character B.',
  },
  ja: {
    'header.preview': '縦に合成をプレビュー',
    'header.reset': 'リセット',
    'header.language': '言語',
    'preview.title': '4コマ合成プレビュー',
    'preview.download': 'PNGをダウンロード',
    'preview.close': '閉じる',
    'confirm.cancel': 'キャンセル',
    'confirm.overwrite': '上書きする',
    'canvas.title': 'キャンバス編集',
    'canvas.draw': '描く',
    'canvas.erase': '消す',
    'canvas.thickness': '太さ',
    'canvas.clear': 'クリア',
    'canvas.save': '保存',
    'form.tone': 'トーン',
    'form.artStyle': '絵柄スタイル',
    'shot.wide.label': 'ワイド（導入）',
    'shot.wide.title': '情景や位置関係を見せる広めの画角',
    'shot.waist.label': 'ウエストショット',
    'shot.waist.title': '胸〜腰までのミディアム構図',
    'shot.closeup_A.label': 'A クローズアップ',
    'shot.closeup_A.title': 'Aの表情を強調',
    'shot.closeup_B.label': 'B クローズアップ',
    'shot.closeup_B.title': 'Bの表情を強調（B使用時）',
    'shot.two_shot.label': 'ツーショット',
    'shot.two_shot.title': 'AとBの関係性が分かる並び（B使用時）',
    'shot.reaction_A.label': 'A リアクション',
    'shot.reaction_A.title': 'Aの反応・ツッコミなどを強調',
    'shot.reaction_B.label': 'B リアクション',
    'shot.reaction_B.title': 'Bの反応を強調（B使用時）',
    'shot.ots_A.label': 'A 肩越し',
    'shot.ots_A.title': 'Aの肩越しに相手/対象を見せる',
    'shot.ots_B.label': 'B 肩越し',
    'shot.ots_B.title': 'Bの肩越しに相手/対象を見せる（B使用時）',
    'story.boke_tsukkomi': 'ボケ→ツッコミ→逆転オチ',
    'story.kishotenketsu': '起承転結',
    'story.running_gag': 'ボケ再起（再ボケ）',
    'story.misunderstanding': '誤解系',
    'story.slice_of_life': '日常系',
    'story.meta': 'メタ系',
    'story.heartful_blunder': 'ハートフル→ドジ→救済',
    'story.absurd_silence_meta': '不条理→沈黙→メタ落ち',
    'tone.mono-screen': 'モノクロ（網点）',
    'tone.line-bold': '太線・高コントラスト',
    'tone.soft-mono': 'やわらかモノクロ',
    'tone.shonen-ink': '少年漫画（スピード線/迫力）',
    'tone.shojo-mono': '少女漫画（繊細/きらめき）',
    'tone.seinen-real': '青年漫画（写実/トーン重め）',
    'tone.gekiga': '劇画（陰影/硬派）',
    'tone.retro-90s': '90年代風（レトロ網点）',
    'tone.horror-ink': 'ホラー（ベタ/スクラッチ）',
    'tone.sumi-brush': '墨筆（筆致/かすれ）',
    'tone.hatch': '影ハッチング',
    'tone.chibi-gag': 'デフォルメ/ギャグ',
    'tone.flat-color': 'フラットカラー',
    'tone.pastel-color': 'パステルカラー',
    'tone.webtoon-color': 'ウェブトゥーン（カラー）',
    'panel.noShot': '構成なし（任意）',
    'placeholder.notGenerated': '未生成',
    'overlay.generatingCharacter': 'キャラ画像を生成中…',
    'overlay.composingImages': '画像を合成中…',
    'overlay.generatingScript': '脚本を生成中…',
    'overlay.generatingPanels': '4コマを作成中…',
    'alert.characterGenFailed': 'キャラ生成に失敗しました',
    'alert.panelGenFailed': '生成に失敗しました',
    'alert.mergeFailed': '合成に失敗しました',
    'alert.scriptGenFailed': '脚本生成に失敗しました',
    'confirm.resetAll': '全体をリセットします。よろしいですか？',
    'confirm.replaceCanvas': 'キャンバスの内容を選択した画像で置き換えます。よろしいですか？',
    'lang.en': '英語',
    'lang.ja': '日本語',
    'card.autoScript.title': '概要から自動脚本生成',
    'card.autoScript.subtitle': '文章を入力するだけで、脚本とキャラクターを自動生成',
    'card.characters.title': 'キャラクター',
    'card.characters.subtitle': '最大2体・参照画像またはAI生成（任意）',
    'form.overview': '概要',
    'placeholder.overviewExample': '例：AがAIを自慢→Bがツッコミ→Aが言い訳→Bの一言で落ちる',
    'option.autoPlan.script': '脚本だけ作る',
    'option.autoPlan.scriptCharacters': '脚本とキャラだけ作る',
    'option.autoPlan.full': '4コマを作成する',
    'button.create': '作成',
    'label.useCharacterB': 'キャラBを使う',
    'button.aiGenerate': 'AI生成',
    'placeholder.characterPrompt': 'スタイル記述子・口調・NGなど',
    'button.addReference': '参照追加',
    'status.draft': '下書き',
    'status.generating': '生成中',
    'status.done': '完了',
    'status.failed': '失敗',
    'panel.edit': 'コマ編集',
    'button.generate': '生成',
    'button.regenerate': '再生成',
    'button.savePng': 'PNG保存',
    'button.savePngWithSpeech': 'PNG(セリフ入り)',
    'panel.script': '脚本',
    'label.description': '描写（状況）',
    'placeholder.descriptionExample': '例：AがPC前で胸を張る。Bは腕を組んで見ている。',
    'label.lineA': 'セリフ（A）',
    'placeholder.lineA': 'Aの短いセリフ',
    'label.lineB': 'セリフ（B）',
    'placeholder.lineB': 'Bの短いセリフ',
    'placeholder.layoutHint': '配置ヒント：A左→B右 など',
    'label.rough': 'ラフ（参考）',
    'label.showTools': 'ツールを表示',
    'button.drawRough': 'ラフを描く',
    'button.loadImage': '画像を読み込む',
    'message.noRough': 'ラフがありません。「ラフを描く」または「画像を読み込む」で追加してください。',
    'confirm.replace': '置き換え',
    'character.A': 'キャラA',
    'character.B': 'キャラB',
    'guide.title': '使い方',
    'guide.message': '内容やスタイルトーンなどを入力し、生成ボタンを押すと自動で4コマ漫画が作成されます。',
    'guide.close': 'OK',
    'tooltip.overview': '自動脚本のための概要を入力します。',
    'tooltip.tone': 'ストーリーのトーンや構成を選択します。',
    'tooltip.artStyle': '全コマに適用する絵柄スタイルを選択します。',
    'tooltip.autoPlan': '自動生成の範囲を選択します。',
    'tooltip.useCharacterB': 'チェックするとキャラBを使用します。',
  },
};
